# Generated by Django 3.2.3 on 2022-07-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название филиала')),
                ('logotype', models.ImageField(max_length=300, unique=True, upload_to='filial/logotype', verbose_name='Логотип')),
                ('status', models.IntegerField(choices=[(0, 'Выключен'), (1, 'Активирован')], default=False, verbose_name='Пол')),
                ('qr_code', models.ImageField(max_length=300, unique=True, upload_to='filial/qr', verbose_name='QR Код')),
                ('widget_type', models.IntegerField(choices=[(0, 'В процентах'), (1, 'В сумме')], default=False, verbose_name='Тип')),
                ('widget_sum', models.IntegerField(default=False, verbose_name='Сумма')),
                ('ids_widget_questions', models.CharField(max_length=100, verbose_name='Вопросы в виджете')),
                ('auth_user', models.ForeignKey(default=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'db_table': 'filial',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип платформы')),
                ('url', models.CharField(max_length=300, verbose_name='Ссылка на филиал')),
                ('filial', models.ForeignKey(default=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.filial', verbose_name='Филиал')),
            ],
            options={
                'db_table': 'rate_platform',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.CharField(max_length=250, verbose_name='Название филиала')),
                ('filial', models.ForeignKey(default=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.filial', verbose_name='Филиал')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
