# Generated by Django 3.2.3 on 2022-07-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не активен'), (1, 'Активирован')], default=False, verbose_name='Пол'),
        ),
    ]
