# Generated by Django 3.2.3 on 2022-07-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0003_filial_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='auth_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='question',
            name='filial',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='filial',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.filial', verbose_name='Филиал'),
        ),
    ]
