# Generated by Django 3.2.3 on 2022-07-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20220719_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='filial',
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
