"""
Django settings for utfservice project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os.path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ux%#sv4stjh*=pqja$vi-&n^_1xnbz#fnh5gi5$8mm@1kxjpv('

# SECURITY WARNING: keep the encrypt key used in production secret!
ENCRYPT_KEY = b"HaB_bB4xSSER-9qt5YXTjeZckrTWsUvR0zsrVV1-IzM="

# API Tokens
API_KEY_YANDEX = '7247c3cb-7bad-4caf-bdc5-12c875936619'
API_KEY_2GIS = 'rurlca3359'
API_KEY_GOOGLE = 'AIzaSyA3Fve6JXGiSWR8UnPZug-gIQlrfI9aTR0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.rectop.ru']

SITE_URL = 'www.rectop.ru'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'rest_framework',
    'django_filters',
    'social_django',
    'qrcode',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'sorl.thumbnail',
    'bootstrap5',
    'Main',
    'Dashboard',
    'Filials',
    'Profile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.AllowAny',
    # ]
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ]
}

ROOT_URLCONF = 'utfservice.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'Main.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'utfservice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'workutf$default',
        'USER': 'workutf',
        'PASSWORD': 'Login12365',
        'HOST': 'workutf.mysql.pythonanywhere-services.com',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#Email configurations

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_USE_TLS = False

EMAIL_USE_SSL = True

EMAIL_PORT =  465

EMAIL_HOST_USER = 'utfrectop@gmail.com'

EMAIL_HOST_PASSWORD = 'yohkvqwtxbtjgecx'


#Social django configurations

AUTHENTICATION_BACKENDS = [
    'social_core.backends.vk.VKOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.yandex.YandexOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_VK_OAUTH2_KEY = '8217035'
SOCIAL_AUTH_VK_OAUTH2_SECRET = '99OkqQImFmUhsKY50eIK'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '669814864745-t3e1fn58hk34l7691vda2nc147kqvvn3.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_YANDEX_OAUTH2_KEY  = 'ad20a4ff0d8047f0983afcdb782cc727'
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = 'a3e66228be3241bc8458d2bf3c228e7b'

#Social auth configurations

LOGIN_REDIRECT_URL = '/'

# Когда появляется ошибка типа "Соответствующий запрос SocialApp не существует", вам необходимо изменить этот ID
SITE_ID = 1

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        'APP': {
            'method': 'oauth2',
            'client_id': 'ad20a4ff0d8047f0983afcdb782cc727',
            'secret': 'a3e66228be3241bc8458d2bf3c228e7b',
            'redirect_uri': SITE_URL+'/accounts/yandex/login/callback/',
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_AUTO_SIGNUP = True


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/workutf/utfservice/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/workutf/utfservice/static'
STATIC_URL = '/static/'
