# Generated by Django 3.2.3 on 2022-07-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verifyCode',
            new_name='verify_code',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
