# Generated by Django 3.2.3 on 2022-07-19 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0002_auto_20220714_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название филиала')),
                ('logotype', models.ImageField(max_length=300, unique=True, upload_to='filial/logotype', verbose_name='Логотип')),
                ('status', models.IntegerField(choices=[(0, 'Не активен'), (1, 'Активирован')], default=False, verbose_name='Пол')),
                ('qr_code', models.ImageField(max_length=300, unique=True, upload_to='filial/qr', verbose_name='QR Код')),
                ('qr_url', models.CharField(default='', max_length=300, verbose_name='Ссылка для QR Кода')),
                ('widget_type', models.IntegerField(choices=[(0, 'В процентах'), (1, 'В сумме')], default=False, verbose_name='Тип')),
                ('widget_sum', models.IntegerField(default=False, verbose_name='Сумма')),
                ('ids_widget_questions', models.CharField(max_length=100, verbose_name='Вопросы в виджете')),
                ('auth_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'db_table': 'filial',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Доп. даннные профиля', 'verbose_name_plural': 'Доп. данные профилей'},
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип платформы')),
                ('url', models.CharField(max_length=300, verbose_name='Ссылка на филиал')),
                ('filial', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Main.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Платформа отзывов',
                'verbose_name_plural': 'Платформы отзывов',
                'db_table': 'rate_platform',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.CharField(max_length=250, verbose_name='Название филиала')),
                ('filial', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Main.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
    ]
