# Generated by Django 3.2.3 on 2022-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20220719_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='logotype',
            field=models.ImageField(max_length=300, upload_to='filial/logotype', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_text',
            field=models.CharField(max_length=250, verbose_name='Содержание'),
        ),
    ]
