# Generated by Django 3.2.3 on 2022-07-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20220719_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='qr_code',
            field=models.ImageField(max_length=300, upload_to='filial/qr', verbose_name='QR Код'),
        ),
    ]
