# Generated by Django 3.2.3 on 2022-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20220719_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='filial',
            name='qr_code_img_url',
            field=models.CharField(default='', max_length=300, verbose_name='QR Код - ссылка на картинку'),
        ),
    ]
