# Generated by Django 3.2.3 on 2022-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20220720_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='logotype',
            field=models.ImageField(max_length=300, upload_to='filial/logotype', verbose_name='Логотип'),
        ),
    ]
