# Generated by Django 3.2.3 on 2022-07-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0008_alter_filial_logotype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='ids_widget_questions',
        ),
        migrations.AlterField(
            model_name='filial',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='widget_type',
            field=models.IntegerField(choices=[(0, 'В процентах'), (1, 'В сумме'), (2, 'Бесплатно')], default=False, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='question',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.filial', verbose_name='Филиал'),
        ),
    ]
