# Generated by Django 3.2.3 on 2022-07-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20220722_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Yandex'), (1, 'Google'), (2, '2GIS')], default=False, verbose_name='Тип платформы'),
        ),
    ]
