# Generated by Django 3.2.3 on 2022-07-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.filial', verbose_name='Филиал'),
        ),
    ]
