# Generated by Django 3.2.3 on 2022-08-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_rate_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 'Очень плохо'), (1, 'Плохо'), (2, 'Неплохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], default=False, verbose_name='Рейтинг')),
                ('content', models.CharField(max_length=5000, verbose_name='Содержание')),
                ('time', models.DateTimeField()),
                ('author_name', models.CharField(max_length=350, verbose_name='Имя рецензента')),
                ('author_url', models.CharField(max_length=1000, verbose_name='Ссылка на рецензента')),
                ('profile_photo_url', models.CharField(max_length=1000, verbose_name='Ссылка на фото профиля')),
                ('relative_time_description', models.CharField(max_length=300, verbose_name='Пояснение по времени')),
                ('filial', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Main.filial', verbose_name='Филиал')),
            ],
        ),
    ]
