# Generated by Django 3.2.3 on 2022-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20220801_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_date_change',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff',
            field=models.IntegerField(choices=[(0, 'Генератор отзывов'), (1, 'Какое-то название'), (2, 'Репутация под ключ')], default=False, verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='profile',
            name='types_answer_review',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='types_load_review',
            field=models.IntegerField(default=0, verbose_name='Количество отгрузок отзывов'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
