# Generated by Django 3.2.3 on 2022-08-02 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20220801_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_change', models.DateTimeField(default=datetime.datetime(2022, 8, 2, 13, 23, 12, 344434))),
                ('types_load_review', models.IntegerField(default=0, verbose_name='Количество отгрузок отзывов')),
            ],
            options={
                'verbose_name': 'Загрузка отзывов',
                'verbose_name_plural': 'Загрузки отзывов',
                'db_table': 'load_reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_date_change',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='types_load_review',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
