# Generated by Django 3.2.3 on 2022-08-03 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20220802_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadReviews',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_date_load_2gis',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 20, 4, 16, 660974)),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_date_load_google',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 20, 4, 16, 660919)),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_date_load_yandex',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 20, 4, 16, 661007)),
        ),
    ]
