# Generated by Django 3.2.3 on 2022-08-04 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20220803_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Yandex'), (1, 'Google'), (2, '2GIS')], default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не прочитано'), (1, 'Прочитано')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_2gis',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 0, 46, 7, 196287)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_google',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 0, 46, 7, 196259)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_yandex',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 0, 46, 7, 196308)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tariff',
            field=models.IntegerField(choices=[(1, 'Генератор отзывов'), (2, 'Какое-то название'), (3, 'Репутация под ключ')], default=0, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verify_code',
            field=models.TextField(blank=True, default='Авторизован через соц.сети', max_length=200),
        ),
    ]
