# Generated by Django 3.2.3 on 2022-08-10 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0021_auto_20220805_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_2gis',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 4, 17, 335622)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_google',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 4, 17, 335598)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_yandex',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 4, 17, 335638)),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(0, 'Yandex'), (1, 'Google'), (2, '2GIS')], default=False)),
                ('id_organization', models.CharField(max_length=200, verbose_name='Id организации')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт с сервисов',
                'verbose_name_plural': 'Аккаунты с сервисов',
                'db_table': 'platform_accounts',
            },
        ),
    ]
