# Generated by Django 3.2.3 on 2022-08-10 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20220810_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='status',
            field=models.IntegerField(choices=[(0, 'Подгружен с сервиса'), (1, 'Подключен'), (2, 'Приостановлен')], default=False, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_2gis',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 44, 52, 822393)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_google',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 44, 52, 822350)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_date_load_yandex',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 44, 52, 822408)),
        ),
    ]
