# Generated by Django 3.2.3 on 2022-08-12 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0024_auto_20220810_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(blank=True, max_length=200, verbose_name='Название организации')),
                ('phone_number', models.IntegerField(blank=True, default=False, verbose_name='Номер телефона')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Полное имя')),
                ('verify_code', models.TextField(blank=True, default='Авторизован через соц.сети', max_length=200)),
                ('tariff', models.IntegerField(choices=[(1, 'Генератор отзывов'), (2, 'Какое-то название'), (3, 'Репутация под ключ')], default=0, verbose_name='Тариф')),
                ('types_answer_review', models.IntegerField(default=0, verbose_name='Количество ответов')),
                ('last_date_load_google', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 56, 49, 601692))),
                ('last_date_load_2gis', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 56, 49, 601718))),
                ('last_date_load_yandex', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 56, 49, 601734))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доп. даннные профиля',
                'verbose_name_plural': 'Доп. данные профилей',
                'db_table': 'additional_user_info',
            },
        ),
        migrations.RenameModel(
            old_name='Platform',
            new_name='PlatformAccount',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='filial',
        ),
        migrations.AlterModelTable(
            name='platformaccount',
            table='platform_account',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
