# Generated by Django 3.2.3 on 2022-08-15 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0025_auto_20220812_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonuserinfo',
            name='last_date_load_2gis',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 21, 19, 6, 391607)),
        ),
        migrations.AlterField(
            model_name='addonuserinfo',
            name='last_date_load_google',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 21, 19, 6, 391575)),
        ),
        migrations.AlterField(
            model_name='addonuserinfo',
            name='last_date_load_yandex',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 21, 19, 6, 391624)),
        ),
        migrations.AlterField(
            model_name='filial',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.platformaccount', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец аккаунта'),
        ),
    ]
