# Generated by Django 3.2.3 on 2022-08-15 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20220815_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonuserinfo',
            name='last_date_load_2gis',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 21, 33, 44, 198837)),
        ),
        migrations.AlterField(
            model_name='addonuserinfo',
            name='last_date_load_google',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 21, 33, 44, 198797)),
        ),
        migrations.AlterField(
            model_name='addonuserinfo',
            name='last_date_load_yandex',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 21, 33, 44, 198864)),
        ),
    ]
