# Generated by Django 3.2.3 on 2022-08-18 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_auto_20220815_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonuserinfo',
            name='last_date_load_2gis',
        ),
        migrations.RemoveField(
            model_name='addonuserinfo',
            name='last_date_load_google',
        ),
        migrations.RemoveField(
            model_name='addonuserinfo',
            name='last_date_load_yandex',
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='last_date_load',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 22, 15, 40, 326233)),
        ),
    ]
