# Generated by Django 3.2.3 on 2022-08-19 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_auto_20220818_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonuserinfo',
            name='types_answer_review',
        ),
        migrations.RemoveField(
            model_name='platformaccount',
            name='last_date_load',
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='last_date_load_filials',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 20, 37, 52, 953241)),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 20, 37, 52, 953200)),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='types_answer_review',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
    ]
