# Generated by Django 3.2.3 on 2022-08-19 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_auto_20220819_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='auth_user',
            new_name='platform_account',
        ),
        migrations.RemoveField(
            model_name='addonuserinfo',
            name='name_organization',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='platform',
        ),
        migrations.AddField(
            model_name='addonuserinfo',
            name='name_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Юр. Лицо'),
        ),
        migrations.AddField(
            model_name='filial',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Адрес филиала'),
        ),
        migrations.AddField(
            model_name='filial',
            name='id_platform_filial',
            field=models.CharField(default='', max_length=200, verbose_name='Id филиала на платформе'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='name_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='review',
            name='id_platform_review',
            field=models.CharField(default='', max_length=200, verbose_name='Id отзыва на платформе'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='id_organization',
            field=models.CharField(default='', max_length=200, verbose_name='Id организации'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_filials',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 31, 59, 485269)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 31, 59, 485243)),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Содержание'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Содержание')),
                ('review', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Main.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ на отзыв',
                'verbose_name_plural': 'Ответы на отзывы',
                'db_table': 'answer_review',
            },
        ),
    ]
