# Generated by Django 3.2.3 on 2022-08-22 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_auto_20220819_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_filials',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 20, 54, 54, 59906)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 20, 54, 54, 59876)),
        ),
    ]
