# Generated by Django 3.2.3 on 2022-08-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20220822_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='qr_code_img_url',
            field=models.ImageField(max_length=300, upload_to='filial/qrcode', verbose_name='QR Код - ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_filials',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 22, 44, 39, 619971)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 22, 44, 39, 619941)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Yandex'), (1, '2GIS'), (2, 'Google')], default=False),
        ),
    ]
