# Generated by Django 3.2.3 on 2022-08-26 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_auto_20220824_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='answerable',
            field=models.IntegerField(choices=[(0, 'Нельзя отвечать'), (1, 'Можно отвечать')], default=1),
        ),
        migrations.AlterField(
            model_name='filial',
            name='status',
            field=models.IntegerField(choices=[(0, 'Подгружен с сервиса'), (1, 'Активирован'), (2, 'Невидимый')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_filials',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 21, 29, 50, 765541)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 21, 29, 50, 765512)),
        ),
    ]
