# Generated by Django 3.2.3 on 2022-08-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_auto_20220826_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 1, 57, 3, 7791)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_filials',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 1, 57, 3, 7173)),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 1, 57, 3, 7142)),
        ),
    ]
